# Configurations
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
rouge: pygments
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Welcome to star6973'
tagline:          
description:      'A blog using Jekyll Metro'
url:              'http://192.168.1.11:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'MH.Ji'

#Social Media links (Use complete URL except for email)
dribbble:       
email:          'battlesun99@gmail.com'
facebook:       'https://www.facebook.com/profile.php?id=100043450430647'
flickr:         
github:         'https://github.com/star6973/cse_project'
gplus:           
instagram:      
pinterest:      
linkedin:       
rss:            
stackoverflow:  
twitter:        

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2

remote_theme: olakara/JekyllMetro
url:  "https://star6973.github.io"
baseurl:  ""
